[workspace]
resolver = "2"
members = [ "movie-*" ]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1"
anyhow = "1"
tokio = { version = "1", features = ["full"] }