name: Rust

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    SQLX_VERSION: 0.7.4
    CARGO_TERM_COLOR: always

jobs:
    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt
            - name: Run cargo fmt
              run: |
                  cargo fmt --all -- --check
    test:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: qwer1234
                    MYSQL_DATABASE: nba-data
                ports:
                    - 3306:3306
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
            - uses: swatinem/rust-cache@v2
              with:
                  key: sqlx-${{ env.SQLX_VERSION }}
            - name: Install sqlx-cli
              run: |
                  cargo install sqlx-cli --version=${{ env.SQLX_VERSION }}
            - name: Migrate database
              run: |
                  cd nba-server
                  sqlx database create
                  sqlx migrate run
            - name: Run cargo test & clippy
              run: |
                  cargo test & 
                  cargo clippy --all-targets --all-features -- -D warnings &
                  wait